version: "3.6"

networks:
  tortuga-network:
    name: 'tortuga-network'
    driver: 'bridge'

volumes:
  rails_database:
    name: rails_database
    driver: local

services:
  app:
    image: tortuga-backend:latest
    env_file:
      - .env
    # environment:
    #   POSTGRES_USER: "${DATABASE_USER}"
    #   POSTGRES_PASSWD: "${DATABASE_PASSWORD}"
    #   RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    ports:
      - 3000:3000
    networks:
      - tortuga-network
      
  postgres:
    image: postgres:14
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - rails_database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DATABASE}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - tortuga-network