version: "3.6"

networks:
  tortuga-network:
    name: 'tortuga-network'
    driver: 'bridge'

volumes:
  tortuga-rails-database:
    name: tortuga-rails-database
    driver: local
  tortuga-bundle-cache:
    name: tortuga-bundle-cache
    driver: local

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - tortuga-rails-database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${DATABASE}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - tortuga-network

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: tortuga-backend:latest
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - tortuga-network
    environment:
      DATABASE: "${DATABASE}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      RAILS_ENV: "${RAILS_ENV}"

